repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: name-tests-test
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-docstring-first
    -   id: check-case-conflict
    -   id: check-added-large-files
    -   id: debug-statements

-   repo: https://github.com/ambv/black
    rev: "24.3.0"
    hooks:
      - id: black
        language_version: python3.11.8
        stages: [commit]
        entry: black
        types: [python]

-   repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        files: \.py$
        stages: [commit]
        language: system
        types: [python]
        args: [--ignore, "W503,E203,E501"]

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v3.0.0a5'
    hooks:
    - id: pylint
      stages: [commit]
      files: \.py$
      language: system
      types: [python]
      args: [--extension-pkg-whitelist,'pydantic',--disable,'C,R,W']
